services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    expose:
      - "3306"